# Generated by Django 5.1.1 on 2024-10-05 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Groups_ics',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Groups_mobile',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mitigations',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mitigations_ics',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mitigations_mobile',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Software_ics',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Software_mobile',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Taktiks',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Taktiks_ics',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Taktiks_mobile',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Techniques_ics',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Techniques_mobile',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_groups_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.groups')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_groups_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('group_ics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.groups_ics')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_groups_M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('group_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.groups_mobile')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_miti_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('mitigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.mitigations')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_miti_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('mitigation_ics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.mitigations_ics')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_miti_M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('mitigation_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.mitigations_mobile')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_soft_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.software')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_soft_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('software_ics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.software_ics')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_soft_M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('software_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.software_mobile')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_tac_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('taktik_ics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.taktiks_ics')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_tac_M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('taktik_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.taktiks_mobile')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_tact_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('taktik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.taktiks')),
            ],
        ),
        migrations.CreateModel(
            name='Url_Refs_Tech_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.techniques')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_tech_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('technique_ics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.techniques_ics')),
            ],
        ),
        migrations.CreateModel(
            name='URL_Refs_tech_M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.URLField(max_length=500)),
                ('technique_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oberflaeche.techniques_mobile')),
            ],
        ),
    ]
