# Generated by Django 5.1.1 on 2024-09-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oberflaeche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('external_reference', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mitigations',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('external_reference', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('external_reference', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Taktiks',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('external_reference', models.TextField(max_length=1000)),
            ],
        ),
    ]
