# Generated by Django 5.1.1 on 2024-10-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oberflaeche', '0002_campaignsics_groups_campaignsics_software_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlreferencescampaignsics',
            old_name='campaign',
            new_name='campaign_ics',
        ),
    ]
