# Generated by Django 5.1.1 on 2024-09-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oberflaeche', '0003_delete_techniques'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('external_reference', models.TextField(max_length=1000)),
            ],
        ),
    ]
